# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Build with Gradle
        run: ./gradlew browserDistribution
      - name: Deploy reitstall-goldberghof.de
        if: "!contains(github.event_name, 'pull_request')"
        uses: SamKirkland/FTP-Deploy-Action@3.1.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}/reitstall-goldberghof
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          known-hosts: ${{ secrets.FTP_HOST_KEY }}
          git-ftp-args: --remote-root reitstall-goldberghof/
          local-dir: reitstall-goldberghof.de/build/distributions/
      - name: comment PR
        if: "contains(github.event_name, 'pull_request')"
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Link to develop page: https://dev.lp42.ch/reitstall-goldberghof"
          check_for_duplicate_msg: true