# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Build with Gradle
        run: ./gradlew browserDistribution
      - name: Upload bundle
        uses: actions/upload-artifact@master
        with:
          name: reitstall-goldberghof.de # Upload artifact with name `dist`
          path: reitstall-goldberghof.de/build/distributions # Upload content of `dist` folder
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download bundle
        uses: actions/download-artifact@master
        with:
          name: reitstall-goldberghof.de # Download artifact named `my_artifact_name` (matches build step: Upload bundle)
          path: dist # Optional, downloads to current working directory under folder {artifact_name} if not specified
      - name: Install lftp
        run: sudo apt update && sudo apt install -y lftp
      - name: Add known host
        run: mkdir -v -p ~/.ssh && chmod 700 ~/.ssh && echo ${{ secrets.FTP_HOST_KEY }} > ~/.ssh/known_hosts
      - name: Upload to FTP
        if: "!contains(github.event_name, 'pull_request')"
        run: lftp ${{ secrets.FTP_SERVER }} -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "mirror --reverse --continue --dereference --delete dist reitstall-goldberghof; quit"
      - name: comment PR
        if: "contains(github.event_name, 'pull_request')"
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Link to develop page: https://dev.lp42.ch/reitstall-goldberghof"
          check_for_duplicate_msg: true
